openapi: 3.0.0
info:
  title: Assertions
  version: 0.49.0
tags: []
paths: {}
components:
  schemas:
    Assertions:
      type: object
      properties:
        score:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
        value:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          maximum: 1
          exclusiveMaximum: true
        widgetId:
          type: string
          pattern: '[a-z-]+'
          minLength: 2
          maxLength: 64
        wishes:
          type: array
          items:
            type: string
          minItems: 1
          maxItems: 3
