openapi: 3.0.0
info:
  title: OneOfWithDiscriminator
  version: 0.49.0
tags: []
paths: {}
components:
  schemas:
    Cat:
      type: object
      required:
        - kind
      properties:
        kind:
          type: string
          enum:
            - cat
        meow:
          type: integer
          format: int32
    Dog:
      type: object
      required:
        - kind
      properties:
        kind:
          type: string
          enum:
            - dog
        bark:
          type: string
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: kind
        mapping:
          cat: '#/components/schemas/Cat'
          dog: '#/components/schemas/Dog'
