openapi: 3.0.0
info:
  title: AllOf
  version: 0.47.1
tags: []
paths: {}
components:
  schemas:
    Cat:
      type: object
      properties:
        meow:
          type: integer
          format: int32
      required:
        - meow
      allOf:
        - $ref: '#/components/schemas/Pet'
    Dog:
      type: object
      properties:
        bark:
          type: string
      required:
        - bark
      allOf:
        - $ref: '#/components/schemas/Pet'
    Pet:
      type: object
      properties:
        name:
          type: string
      required:
        - name
