openapi: 3.0.0
info:
  title: Nullable
  version: 0.47.1
tags: []
paths: {}
components:
  schemas:
    Flex:
      type: object
      required:
        - mightBeNull
      properties:
        mightBeNull:
          $ref: '#/components/schemas/NullableString'
    NullableString:
      type: string
      nullable: true
