openapi: 3.0.0
info:
  title: AnyOf
  version: 0.47.1
tags: []
paths: {}
components:
  schemas:
    Cat:
      type: object
      properties:
        meow:
          type: integer
          format: int32
    Dog:
      type: object
      properties:
        bark:
          type: string
    Pet:
      anyOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
