openapi: 3.0.0
info:
  title: Request Body
  version: 0.49.0
tags: []
paths:
  /body:
    post:
      operationId: Body_explicit
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
    put:
      operationId: Body_implicit
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
  /widgets:
    post:
      operationId: Widgets_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
    put:
      operationId: Widgets_uploadImage
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          image/png:
            schema:
              type: string
              format: binary
  /widgets:multi:
    post:
      operationId: Widgets_analyze
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
          application/pdf:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
  /widgets:process:
    post:
      operationId: Process_process_Process_process2
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
          text/csv:
            schema:
              type: string
components:
  schemas:
    Widget:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          readOnly: true
        weight:
          type: integer
          format: int32
        color:
          type: string
          enum:
            - red
            - blue
    Widgets.Process.CsvBody:
      type: object
      required:
        - _
      properties:
        _:
          type: string
