openapi: 3.0.0
info:
  title: Response Object
  version: 0.49.0
tags:
  - name: Headers
paths:
  /widgets/{id}:
    get:
      operationId: Widgets_read
      parameters:
        - $ref: '#/components/parameters/Widgets.WidgetId'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
    post:
      operationId: Widgets_getImage
      parameters:
        - $ref: '#/components/parameters/Widgets.WidgetId'
      responses:
        '200':
          description: The request has succeeded.
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
            image/png:
              schema:
                type: string
                format: binary
  /widgets/{id}/analyze:
    post:
      operationId: Widgets_analyze
      parameters:
        - $ref: '#/components/parameters/Widgets.WidgetId'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
            text/html:
              schema:
                type: string
            image/jpeg:
              schema:
                type: string
                format: binary
  /widgets/{id}/droidCheck:
    post:
      operationId: Widgets_droidCheck
      parameters:
        - $ref: '#/components/parameters/Widgets.WidgetId'
      responses:
        '204':
          description: These are not the droids you are looking for.
  /widgets/{id}:headers:
    get:
      tags:
        - Headers
      operationId: Widgets_headers
      parameters:
        - $ref: '#/components/parameters/Widgets.WidgetId'
      responses:
        '200':
          description: The request has succeeded.
          headers:
            x-rate-limit-remaining:
              required: true
              schema:
                type: number
            x-rate-limit-reset:
              required: false
              schema:
                type: number
          content:
            application/json:
              schema:
                type: string
components:
  parameters:
    Widgets.WidgetId:
      name: id
      in: path
      required: true
      schema:
        type: string
  schemas:
    Widget:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          readOnly: true
        weight:
          type: integer
          format: int32
        color:
          type: string
          enum:
            - red
            - blue
    Widgets.JediResponse:
      type: object
      description: These are not the droids you are looking for.
