openapi: 3.0.0
info:
  title: Discriminator
  version: 0.49.0
tags: []
paths: {}
components:
  schemas:
    Cat:
      type: object
      required:
        - kind
      allOf:
        - $ref: '#/components/schemas/Pet'
      properties:
        kind:
          type: string
          enum:
            - cat
        meow:
          type: integer
          format: int32
    Dog:
      type: object
      required:
        - kind
      allOf:
        - $ref: '#/components/schemas/Pet'
      properties:
        kind:
          type: string
          enum:
            - dog
        bark:
          type: string
    Pet:
      type: object
      discriminator:
        propertyName: kind
        mapping:
          cat: '#/components/schemas/Cat'
          dog: '#/components/schemas/Dog'
      required:
        - name
      properties:
        kind:
          type: string
          description: Discriminator property for Pet.
        name:
          type: string
        weight:
          type: number
          format: float
