openapi: 3.0.0
info:
  title: Paths
  version: 0.49.0
tags: []
paths:
  /widgets:
    post:
      operationId: Widgets_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
  /widgets/{id}:
    get:
      operationId: Widgets_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
  /widgets/{id}/parts:
    get:
      operationId: Parts_list
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'
components:
  schemas:
    Gadget:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        size:
          type: string
          enum:
            - small
            - medium
            - large
            - x-large
    Part:
      type: object
      required:
        - id
        - description
      properties:
        id:
          type: string
        description:
          type: string
    Widget:
      type: object
      required:
        - id
        - weight
        - color
      properties:
        id:
          type: string
          readOnly: true
        weight:
          type: integer
          format: int32
        color:
          type: string
          enum:
            - red
            - blue
