openapi: 3.0.0
info:
  title: ReadOnly
  version: 0.49.0
tags: []
paths: {}
components:
  schemas:
    Widget:
      type: object
      required:
        - id
        - description
        - weight
      properties:
        id:
          type: string
          readOnly: true
        description:
          type: string
        weight:
          type: number
          format: float
