openapi: 3.0.0
info:
  title: Additional Properties
  version: 0.47.1
tags: []
paths: {}
components:
  schemas:
    Foo:
      type: object
      additionalProperties: {}
    FooBar:
      type: object
      properties:
        bar:
          type: string
      required:
        - bar
      allOf:
        - type: object
          additionalProperties: {}
      additionalProperties: {}
    FooBaz:
      type: object
      properties:
        baz:
          type: object
          additionalProperties:
            type: string
      required:
        - baz
